// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// setpgid
int setpgid(int x);
RcppExport SEXP _pbmcapply_setpgid(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(setpgid(x));
    return rcpp_result_gen;
END_RCPP
}
// killp
int killp(int pgid);
RcppExport SEXP _pbmcapply_killp(SEXP pgidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type pgid(pgidSEXP);
    rcpp_result_gen = Rcpp::wrap(killp(pgid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pbmcapply_setpgid", (DL_FUNC) &_pbmcapply_setpgid, 1},
    {"_pbmcapply_killp", (DL_FUNC) &_pbmcapply_killp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_pbmcapply(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
