# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setpgid <- function(x) {
    .Call(`_pbmcapply_setpgid`, x)
}

killp <- function(pgid) {
    .Call(`_pbmcapply_killp`, pgid)
}

